name: Sync PKGBUILD version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-version:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install required tools
        run: |
          pacman -Sy --noconfirm base-devel git nodejs npm pacman-contrib

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
          persist-credentials: true

      - name: Get package.json version
        id: pkgjson
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get PKGBUILD version
        id: pkgbuild
        run: |
          VERSION=$(grep '^pkgver=' PKGBUILD | cut -d= -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Sync PKGBUILD version
        run: |
          PKGJSON_VERSION="${{ steps.pkgjson.outputs.version }}"

          sed -i "s/^pkgver=.*/pkgver=$PKGJSON_VERSION/" PKGBUILD

      - name: Generate .SRCINFO
        run: |
          runuser -u nobody -- makepkg --printsrcinfo > .SRCINFO

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: sync PKGBUILD version + update .SRCINFO"
          push_options: --force